# Generated by Django 5.2.5 on 2025-08-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=18)),
                ('contact_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(default='novo', max_length=20)),
            ],
            options={
                'verbose_name': 'Lead Empresarial',
                'verbose_name_plural': 'Leads Empresariais',
                'ordering': ('-created_at',),
            },
        ),
    ]
