# Generated by Django 4.2 on 2025-09-14 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_site', '0002_businesslead'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoEmpresarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('velocidade', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('destaque', models.BooleanField(default=False)),
                ('whatsapp_text', models.CharField(default='Olá! Quero contratar este plano.', max_length=255)),
            ],
        ),
    ]
