# Generated by Django 5.1.6 on 2025-09-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_site', '0004_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(max_length=200),
        ),
    ]
